openapi: 3.0.0
info:
  title: Express API
  description: API for managing users and tasks
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/users:
    get:
      summary: Get all users
      description: Fetch all users. Accessible only by admins.
      operationId: getAllUsers
      security:
        - jwt: []
      tags:
        - Users
      responses:
        '200':
          description: Successfully retrieved users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: user1
                    email:
                      type: string
                      example: user1@example.com
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin privileges required)

    post:
      summary: User signup
      description: Register a new user. Requires email and password validation.
      operationId: signup
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User successfully created
        '400':
          description: Bad request (validation errors)
        '409':
          description: Conflict (email or username already taken)

  /api/users/login:
    post:
      summary: User login
      description: Login to the application by providing a username and password.
      operationId: login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request (missing or invalid data)
        '401':
          description: Unauthorized (invalid credentials)

  /api/tasks:
    get:
      summary: Get tasks
      description: Retrieve a list of tasks. Requires proper query parameters.
      operationId: getTasks
      security:
        - jwt: []
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          description: Filter tasks by status
          required: false
          schema:
            type: string
            enum:
              - pending
              - completed
        - name: assignedTo
          in: query
          description: Filter tasks by the user assigned
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    assignedTo:
                      type: string
                    dueDate:
                      type: string
                      format: date
        '400':
          description: Bad request (invalid query parameters)
        '401':
          description: Unauthorized

    post:
      summary: Create a new task
      description: Adds a new task to the system. Admins are prohibited from creating tasks.
      operationId: addTask
      security:
        - jwt: []
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                dueDate:
                  type: string
                  format: date
              required:
                - title
                - description
      responses:
        '201':
          description: Task successfully created
        '400':
          description: Bad request (validation errors)
        '403':
          description: Forbidden (admins are prohibited from creating tasks)
        '401':
          description: Unauthorized

    put:
      summary: Edit an existing task
      description: Modify the details of an existing task.
      operationId: editTask
      security:
        - jwt: []
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: ID of the task to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
              required:
                - title
                - description
      responses:
        '200':
          description: Task successfully updated
        '400':
          description: Bad request (validation errors)
        '404':
          description: Task not found
        '401':
          description: Unauthorized

    delete:
      summary: Delete a task
      description: Remove a task from the system.
      operationId: removeTask
      security:
        - jwt: []
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: ID of the task to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task successfully deleted
        '404':
          description: Task not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
